vario_prac : vario_practice.o #test.o
	gcc -o vario_prac vario_practice.o #test.o

vario_practice.o : vario_practice.c
	gcc -c vario_practice.c

#test.o : test.c
#	gcc -c test.c

clean :
	rm vario_prac vario_practice.o #test.o
